name: serverstatus
env:
  tcpvalid: ${{ secrets.SERVER_TCP }}
  udpvalid: ${{ secrets.SERVER_UDP }}
  urlvalid: ${{ secrets.SERVER_URL }}
  
on:
  schedule:
  - cron: "*/9 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          
      - name: check tcp server status
        id: check-tcp-server-status
        run: |
          rm README.md && touch README.md
          echo "# Server Status" | tee -a README.md
          echo "Check server status support tcp udp url" | tee -a README.md
          echo "> This README is generated every ${{ secrets.CRON_MIN_INTERVAL }} minures by Github action." | tee -a README.md
          echo "## Last updated:" | tee -a README.md
          date | tee -a README.md
          echo "## TCP status: " | tee -a README.md
          echo "|Domain/IP|Port|**Status**|" |tee -a README.md
          echo "|--|--|--|" |tee -a README.md
          echo "tcpvalid: ${tcpvalid}"
          echo "${tcpvalid}" | while read name port; 
          do
            name_output=$(echo $name | sed 's/,//g')
            nc -v -w 3 -z $name $port &>/dev/null && echo "|$name_output|$port|Online :white_check_mark:|" || echo "|$name_output|$port| Offline ! :x:|" 
            sleep 1
          done | tee -a README.md
          
      - name: check udp server status
        id: check-udp-server-status
        run: |
          echo "## UDP status: " | tee -a README.md
          echo "|Domain/IP|Port|**Status**|" |tee -a README.md
          echo "|--|--|--|" |tee -a README.md
          echo "udpvalid: ${udpvalid}"
          echo "${udpvalid}" | while read name port; 
          do
            name_output=$(echo $name | sed 's/,//g')
            nc -v -w 3 -z $name $port &>/dev/null && echo "|$name_output|$port|Online :white_check_mark:|" || echo "|$name_output|$port| Offline ! :x:|" 
            sleep 1
          done | tee -a README.md
          
      - name: check website status
        id: check-website-status
        run: |
          echo "## website status: " | tee -a README.md
          echo "|Domain/IP|Code|**Status**|" |tee -a README.md
          echo "|--|--|--|" |tee -a README.md
          echo "urlvalid: ${urlvalid}|${{ secrets.GITHUB_TOKEN }}|"
          echo "${urlvalid}" | while read name code;
          do
            name_output=$(echo $name | sed 's/,//g')
            status=$(curl -sI $name | head -1 | awk '{print $2}'); [ $status -eq $code ] && echo "|$name_output|$port|Online :white_check_mark:|" || echo "|$name_output|$port| Offline ! :x:|"
            sleep 1
          done | tee -a README.md
          
      - name: Commit files
        run: |
          git config --local user.email "caojtop@outlook.com"
          git config --local user.name "caojtop@outlook.com"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
